### ISSUE TITLE
The program stops working when close button is clicked in RemoveNodesConfirmationDialog

### ISSUE THREAD

**Issue by CIRCULARKA** [IngvarX/Camelot#19]
When I click on close button in this dialog it stops the program and then it leads to closening. I talking about system close button (red cross) - not about the costume one
![image](https://user-images.githubusercontent.com/34581740/86493586-805e7800-bd8b-11ea-9b7c-5661cf1b80ce.png)
![image](https://user-images.githubusercontent.com/34581740/86493609-953b0b80-bd8b-11ea-97db-7805c31808a8.png)

**Comment by IngvarX** [comment]
Fixed in master branch
