### ISSUE TITLE
Design for "Open With" modal

### ISSUE THREAD

**Issue by pkrasicki** [IngvarX/Camelot#23]
![camelot-open-with-modal](https://user-images.githubusercontent.com/49721209/96285280-4168d100-0fce-11eb-9bf0-618ba658a2df.png)

![camelot-open-with-modal2](https://user-images.githubusercontent.com/49721209/96285306-4ded2980-0fce-11eb-84ac-5c9839e56971.png)

Icons used will depend on file type and on the apps.

**Comment by IngvarX** [comment]
Merged into master
