### ISSUE TITLE
Design for light theme

### ISSUE THREAD

**Issue by pkrasicki** [IngvarX/Camelot#27]
![camelot-filemanager-ui38-light1](https://user-images.githubusercontent.com/49721209/102794813-d22fa480-43a3-11eb-8580-eda6517c577f.png)

![camelot-filemanager-ui38-light2](https://user-images.githubusercontent.com/49721209/102794863-e1165700-43a3-11eb-99a4-33e1c66b4960.png)

![camelot-filemanager-ui38-light3](https://user-images.githubusercontent.com/49721209/102794894-ea9fbf00-43a3-11eb-8317-9fcfa1dd5609.png)

![camelot-filemanager-ui38-light4](https://user-images.githubusercontent.com/49721209/102794921-f5f2ea80-43a3-11eb-95f3-56b2780cc420.png)

![camelot-filemanager-ui38-light5](https://user-images.githubusercontent.com/49721209/102794950-fbe8cb80-43a3-11eb-9523-ecc737fd8281.png)

![camelot-filemanager-ui38-light7](https://user-images.githubusercontent.com/49721209/102794975-073bf700-43a4-11eb-840e-6444d21a87eb.png)

**Comment by IngvarX** [comment]
Resolving as white theme is actually already implemented
