### ISSUE TITLE
AUR package

### ISSUE THREAD

**Issue by antikruk** [IngvarX/Camelot#28]
Create please package in AUR

**Comment by IngvarX** [comment]
Hello! 

I added 2 following packages to AUR:

1) camelot-git: https://aur.archlinux.org/packages/camelot-git/
2) camelot: https://aur.archlinux.org/packages/camelot/

Could you please test them?

**Comment by antikruk** [comment]
Thanks
Manjaro Nibia
[CamelotLog-20201225.txt](https://github.com/IngvarX/Camelot/files/5742271/CamelotLog-20201225.txt)

builds from both repositories

1. from https://aur.archlinux.org/packages/camelot-git/ don't starting "
camelot-git
bash: camelot-git: command not found"

2. from https://aur.archlinux.org/packages/camelot/
Don't start without sudo and desktop file is missing

**Comment by IngvarX** [comment]
Try to start first one with command `camelot` too. Second package issue is related to permissions, similar to #26 Will be fixed in next release only

**Comment by IngvarX** [comment]
@antikruk I updated camelot-git package. Should work with `camelot-git` command now. Could you please check it once again?

**Comment by antikruk** [comment]
> @antikruk I updated camelot-git package. Should work with `camelot-git` command now. Could you please check it once again?

Thanks. It's ok

**Comment by IngvarX** [comment]
Great! I will close this issue after fixing `camelot` package
