### ISSUE TITLE
Can't navigate to the parent directory with `Enter`

### ISSUE THREAD

**Issue by MichaelSL** [IngvarX/Camelot#34]
Application version: `v0.2.4`
Package type: Single EXE, Windows

## Steps to reproduce:

1. Start the application.
2. Navigate into the directory.
3. Highlight `[..]` ang hit `Enter`

## Expected behavior:
Navigate to a parent directory

## Actual behavior:
Nothing happens

## Notes:
Mouse double click om `[..]` works.

**Comment by MichaelSL** [comment]
https://user-images.githubusercontent.com/2205113/113800657-f463ed00-971c-11eb-88ae-d269efe76893.mp4

**Comment by IngvarX** [comment]
Hello,

Thanks for your detailed report! Seems to be regression bug. Added a fix in master branch and added Ui test to prevent this from happening again
