### ISSUE TITLE
Drag and drop would be a nice addition.

### ISSUE THREAD

**Issue by sampanna99** [IngvarX/Camelot#35]

**Comment by IngvarX** [comment]
Hi, do you mean files drag n drop? This feature is planned but it will hard because I'm not sure Avalonia supports it out of box for data grids

**Comment by sampanna99** [comment]
Yes, Drag and drop files from one one panel to another or within the same panel. I will try to customize it as well.

**Comment by IngvarX** [comment]
I added experimental support of drag and drop in master branch, still not properly tested though

**Comment by sampanna99** [comment]
Oh wow that was fast. I will clone the repo. Thank you.

**Comment by IngvarX** [comment]
Drag n drop support in Avalonia is limited so seems I implemented everything I could. I'm closing this because I tested drag n drop on all platforms. Will include this feature in next release.
