### ISSUE TITLE
Drive no info

### ISSUE THREAD

**Issue by CreateLab** [IngvarX/Camelot#38]
I cant see any folders in Drives
![изображение](https://user-images.githubusercontent.com/33497292/115409999-efae3700-a1fa-11eb-938c-c2853a8033bd.png)

**Comment by IngvarX** [comment]
Hi, does Camelot has access to this directory?

**Comment by CreateLab** [comment]
Yes. It's just root. And in root i wanna see, that i see in pathfinder. But usually see strage staff.
(Test on 2 win pc)
![изображение](https://user-images.githubusercontent.com/33497292/115433505-538f2a80-a210-11eb-93da-43e1a1a677da.png)

**Comment by IngvarX** [comment]
Fixed in master branch
