### ISSUE TITLE
Bottom bar improvements

### ISSUE THREAD

**Issue by pkrasicki** [IngvarX/Camelot#4]
![camelot_bottom_bar](https://user-images.githubusercontent.com/49721209/80429314-585e1e80-88db-11ea-8c8e-4d29a8caed75.png)

A few things could be improved:
- change hotkey text to less intense color (white with 0.5 opacity looks good)
- change hotkey text to a bit smaller font (perhaps 16px)
- different icon for edit button (like the one on the picture)
- icons are not aligned with text

**Comment by u1035** [comment]
Hello!
May I try to help with it? 
I tried to change font size and opacity of hotkey text and align icons, but I don't know where to get new icon for edit button in geometry path format.
![ca1](https://user-images.githubusercontent.com/30569140/85169686-e370ea80-b274-11ea-80c1-abe9e833d6b0.png)

**Comment by IngvarX** [comment]
Hello! This button acts more like "Open" instead of "Edit" (I don't like how it's done in classical file managers). Not sure what icon we should use in this case. I thought it's better to change button text but keep existing icon. On mockup following icon was used:

    <GeometryDrawing Geometry="M402.6 83.2l90.2 90.2c3.8 3.8 3.8 10 0 13.8L274.4 405.6l-92.8 10.3c-12.4 1.4-22.9-9.1-21.5-21.5l10.3-92.8L388.8 83.2c3.8-3.8 10-3.8 13.8 0zm162-22.9l-48.8-48.8c-15.2-15.2-39.9-15.2-55.2 0l-35.4 35.4c-3.8 3.8-3.8 10 0 13.8l90.2 90.2c3.8 3.8 10 3.8 13.8 0l35.4-35.4c15.2-15.3 15.2-40 0-55.2zM384 346.2V448H64V128h229.8c3.2 0 6.2-1.3 8.5-3.5l40-40c7.6-7.6 2.2-20.5-8.5-20.5H48C21.5 64 0 85.5 0 112v352c0 26.5 21.5 48 48 48h352c26.5 0 48-21.5 48-48V306.2c0-10.7-12.9-16-20.5-8.5l-40 40c-2.2 2.3-3.5 5.3-3.5 8.5z"/>

**Comment by u1035** [comment]
Here are two variants with new icon and "Open"/"Edit" text. 
Or previous icon with eye was better?

(I draw lines to check vertical alignment)

![ca2](https://user-images.githubusercontent.com/30569140/85198113-afd2a680-b2ee-11ea-99d8-d3b35975d757.png)
![ca3](https://user-images.githubusercontent.com/30569140/85198114-b06b3d00-b2ee-11ea-8b23-bb57667297b2.png)

**Comment by IngvarX** [comment]
I think "Open" text with previous icon is better because "Open" text with "Edit" icon is a bit confusing. Also I think new dir icon should be moved down a bit

**Comment by IngvarX** [comment]
Fixed on #8
