### ISSUE TITLE
Paste

### ISSUE THREAD

**Issue by CreateLab** [IngvarX/Camelot#42]
Interesting in "paste" button or hotkey
--------
If i copy file i wanna paste it in current directory in FilesPanelView

**Comment by IngvarX** [comment]
Does ctrl+c and ctrl+v work for you?

**Comment by CreateLab** [comment]
Test. Answer is no
Wanna gif?

**Comment by IngvarX** [comment]
Yes, please. Do you copy file in Camelot or using file explorer/whatever else?

**Comment by CreateLab** [comment]
Yes. Select file in camelot next click cntrl+c next click cntr+v

**Comment by IngvarX** [comment]
I updated some clipboard logic in master branch, could you please check again?

**Comment by IngvarX** [comment]
@CreateLab any updates on this?

**Comment by CreateLab** [comment]
@IngvarX so cool. yes
