### ISSUE TITLE
ReadyToRun broke app

### ISSUE THREAD

**Issue by CreateLab** [IngvarX/Camelot#46]
```
dotnet publish -r win-x64 -c Release /p:PublishSingleFile=true /p:PublishTrimmed=true /p:PublishReadyToRun=true
```
if use this command in netcore 3.1 build fail
 if use with 5.0 build sucsess but app not run at all with no messages

**Comment by CreateLab** [comment]
if u wanna may be assing for me

**Comment by IngvarX** [comment]
What build error do you have?

**Comment by CreateLab** [comment]
![изображение](https://user-images.githubusercontent.com/33497292/120281282-6c840480-c2c1-11eb-9537-9be280fe4788.png)
`Failed to optimize assemblies for performance. You can exclude failed assemblies from optimization or set the property to false ...`

**Comment by IngvarX** [comment]
Could you please retry using latest master? Also it looks like NET 5 SDK was used for building, it might not work at all

**Comment by IngvarX** [comment]
Closing this as not relevant anymore because Camelot uses .NET 6 now
