### ISSUE TITLE
Cannot copy/paste folder (only contents)

### ISSUE THREAD

**Issue by hynow** [IngvarX/Camelot#52]
When trying to copy/paste a folder, it pastes the folder's contents rather than keeping them contained in a folder.

**Comment by IngvarX** [comment]
Hi, could you please provide following info:

1) What OS are you on?
2) What Camelot version are you using?
3) How do you try to copy folder (there are many different options to do that in UI)?

**Comment by hynow** [comment]
1. Windows 10
2. v0.3.0.0 SingleExe
3. It occurs when using ctrl+c/ctrl+v, and when using the right-click menu to copy to clipboard and paste from clipboard, and when right-clicking and choosing copy, and when right-clicking and choosing move.

**Comment by IngvarX** [comment]
Fixed in master branch
