### ISSUE TITLE
Actions within a folder will show duplicated subfolder within the parent folder view until parent view is refreshed

### ISSUE THREAD

**Issue by hynow** [IngvarX/Camelot#57]
Say I have a directory open in the left pane called folder 1, and it has a subfolder called folder 2.  If I have folder 2 open in the right pane and create, delete, or rename any files within folder 2, it will create a duplicate row showing folder 2 within the folder 1 left pane.  It creates a new duplicate row for every action taken within folder 2.

So If I perform ten different actions within folder 2, it will show "folder 2" eleven times within the folder 1 view on the left pane.  Once I refresh the folder 1 view, it goes back to only showing one row of "folder 2".

Windows 10, v0.3.0.0 SingleExe

**Comment by IngvarX** [comment]
Fixed in cd7689af
